name: Flask CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3       # Клонує репозиторій на GitHub Runner

      - name: Set up Python 3.10
        uses: actions/setup-python@v4   # Встановлює Python 3.10

      - name: Cache pip packages
        uses: actions/cache@v3          # Кешує встановлені пакети pip для швидшої роботи
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r flask_app/requirements.txt   # Встановлює всі залежності з requirements.txt

      - name: Run tests
        working-directory: ./flask_app                 # Змінює робочий каталог для команди pytest
        run: pytest tests                              # Запускає тести у папці tests

